feat!: refactor e2e tests for review environments (#393)

diff --git a/.github/workflows/gh-e2e-test.yml b/.github/workflows/gh-e2e-test.yml
--- a/.github/workflows/gh-e2e-test.yml
+++ b/.github/workflows/gh-e2e-test.yml
@@ -3,42 +3,14 @@ name: Run e2e-tests on GitHub
 on:
   workflow_call:
     inputs:
-      allure-version:
-        description: "Allure Report version"
-        type: string
-        default: "2.24.0"
-      allure-report-prefix:
-        description: "Allure report name prefix"
-        type: string
-        default: "allure-report"
-      dotenv-file:
-        description: "Path to dotenv file with E2E test variables"
-        type: string
-        default: "apps/chat-e2e/.env.ci"
       e2e-host:
         required: true
-        description: "The host URL for end-to-end testing"
+        description: "The environment URL for end-to-end testing, e.g., https://my-app.example.com"
         type: string
-      java-distribution:
-        description: "Java distribution"
-        type: string
-        default: "temurin"
-      java-version:
-        description: "Java version"
-        type: string
-        default: "17"
       next-public-overlay-host:
         required: true
-        description: "Overlay domain host"
+        description: "An ai-dial-chat (overlay) URL"
         type: string
-      node-version:
-        description: "NodeJS version"
-        type: string
-        default: "lts/*"
-      playwright-version:
-        description: "Playwright version"
-        type: string
-        default: "latest"
       test-repository:
         description: "E2E tests Git repository"
         type: string
@@ -47,13 +19,41 @@ on:
         description: "E2E tests Git branch"
         type: string
         default: "development"
+      dotenv-file:
+        description: "Path to dotenv file with E2E test variables"
+        type: string
+        default: "apps/chat-e2e/.env.ci"
+      java-distribution:
+        description: "Java distribution"
+        type: string
+        default: "temurin"
+      java-version:
+        description: "Java version"
+        type: string
+        default: "17"
+      node-version:
+        description: "NodeJS version"
+        type: string
+        default: "lts/*"
+      playwright-version:
+        description: "Playwright version"
+        type: string
+        default: "latest"
+      allure-version:
+        description: "Allure Report version"
+        type: string
+        default: "2.24.0"
+      report-prefix:
+        description: "Test report name prefix"
+        type: string
+        default: ${{ github.run_id }}
       timeout-minutes:
         description: "The maximum number of minutes to let a job run before GitHub automatically cancels it."
         type: number
         default: 60
       environment-name:
         default: "e2e-test"
-        description: "The GitHub environment name to use for the test."
+        description: "The GitHub environment name to use for the tests. An abstraction to conveniently store secrets and variables"
         type: string
     secrets:
       E2E_ADMIN:
@@ -88,6 +88,7 @@ jobs:
           repository: ${{ inputs.test-repository }}
           ref: ${{ inputs.test-branch }}
           lfs: true
+          persist-credentials: false
       - uses: falti/dotenv-action@f4656c46de6bc223dda660f6724d52537bc0642a # v1.1.5
         with:
           path: ${{ inputs.dotenv-file }}
@@ -101,85 +102,87 @@ jobs:
         with:
           distribution: ${{ inputs.java-distribution }}
           java-version: ${{ inputs.java-version }}
-      - name: Install Allure
+      - name: Install Allure CLI
         run: |
-          curl -fsSL https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz | tar -xzf -
-          ./allure-${ALLURE_VERSION}/bin/allure --version
+          curl -fsSL --retry 5 --retry-delay 2 https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure_${ALLURE_VERSION}-1_all.deb -o /tmp/allure.deb
+          sudo dpkg -i /tmp/allure.deb
+          echo "Allure CLI version: $(allure --version)"
         shell: bash
         env:
           ALLURE_VERSION: ${{ inputs.allure-version }}
-      - name: Install playwright
+      - name: Install Playwright
         run: |
-          npm install -D @playwright/test@${{ inputs.playwright-version }}
+          npm install -D @playwright/test@${{ inputs.playwright-version }} allure-playwright
           npx playwright install --with-deps
-          # FIXME: Force allure-playwright installation since playwright is removing it
-          npm install -D allure-playwright
-          npx playwright --version
+          echo "Playwright version: $(npx playwright --version)"
         shell: bash
       - name: Wait for environment
         run: |
-          echo "Expected environment URL ${E2E_HOST}, waiting to be available..."
-          ENV_HOSTNAME=$(echo "$E2E_HOST" | awk -F/ '{print $3}')
-          ENV_OVERLAY_HOSTNAME=$(echo "$NEXT_PUBLIC_OVERLAY_HOST" | awk -F/ '{print $3}')
+          #!/bin/bash
+          echo "Expected environment URL ${ENVIRONMENT_URL}, waiting to be available..."
+          env_hostname=$(echo "$ENVIRONMENT_URL" | awk -F/ '{print $3}')
+          env_overlay_hostname=$(echo "$NEXT_PUBLIC_OVERLAY_HOST" | awk -F/ '{print $3}')
 
           wait_for_dns() {
-              DOMAIN="$1"
-              ATTEMPT=0
-              ATTEMPT_LIMIT=90  # retry resolve up to 15 minutes
-              ATTEMPT_DELAY=10  # 10 seconds between resolve attempts
+              local domain="$1"
+              local attempt=0
+              local attempt_limit=90  # retry resolve up to 15 minutes
+              local attempt_delay=10  # 10 seconds between resolve attempts
 
-              if [ -z "$DOMAIN" ]; then
+              if [ -z "$domain" ]; then
                   echo "Specify domain name as first argument" >&2
                   return 1
               fi
 
-              BASE_DOMAIN=$(echo "$DOMAIN" | sed -E 's/[^.]+\.(.+)/\1/')
-              echo "Query Google public DNS for $BASE_DOMAIN nameservers"
-              NS_SERVERS=$(dig +short @8.8.8.8 ns $BASE_DOMAIN)
-              if [ -n "$NS_SERVERS" ]; then
-                  echo "Detected nameservers for $BASE_DOMAIN:"
-                  echo "$NS_SERVERS"
+              local base_domain=$(echo "$domain" | sed -E 's/[^.]+\.(.+)/\1/')
+              echo "Query Google public DNS for $base_domain nameservers"
+              local ns_servers=$(dig +short @8.8.8.8 ns $base_domain)
+              if [ -n "$ns_servers" ]; then
+                  echo "Detected nameservers for $base_domain:"
+                  echo "$ns_servers"
               else
-                  echo "Unable to detect nameservers for $BASE_DOMAIN" >&2
+                  echo "Unable to detect nameservers for $base_domain" >&2
                   return 1
               fi
 
-              for NS in $NS_SERVERS
+              local ns
+              local result
+              for ns in $ns_servers
               do
                   while true
                       do
-                      echo "Query $NS for $DOMAIN"
-                      RESULT=$(dig +short @${NS} "$DOMAIN")
-                      if [ ! -z "$RESULT" ]; then
-                          if echo "$RESULT" | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
-                              echo "$RESULT"
+                      echo "Query $ns for $domain"
+                      result=$(dig +short @${ns} "$domain")
+                      if [ ! -z "$result" ]; then
+                          if echo "$result" | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
+                              echo "$result"
                               break
                           fi
                       fi
-                      ATTEMPT=$((ATTEMPT+1))
-                      if [ $ATTEMPT -le $ATTEMPT_LIMIT ]; then
-                          sleep $ATTEMPT_DELAY
+                      attempt=$((attempt+1))
+                      if [ $attempt -le $attempt_limit ]; then
+                          sleep $attempt_delay
                       else
-                          echo "Unable to resolve $DOMAIN" >&2
+                          echo "Unable to resolve $domain" >&2
                           return 1
                       fi
                   done
               done
           }
 
-          wait_for_dns ${ENV_HOSTNAME}
-          wait_for_dns ${ENV_OVERLAY_HOSTNAME}
+          wait_for_dns ${env_hostname}
+          wait_for_dns ${env_overlay_hostname}
 
-          curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${E2E_HOST}"/api/health
+          curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${ENVIRONMENT_URL}"/api/health
           curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${NEXT_PUBLIC_OVERLAY_HOST}"/api/health
         shell: bash
         env:
-          E2E_HOST: ${{ inputs.e2e-host }}
+          ENVIRONMENT_URL: ${{ inputs.e2e-host }}
           NEXT_PUBLIC_OVERLAY_HOST: ${{ inputs.next-public-overlay-host }}
       - name: Run tests
         run: |
-          echo "Host to run e2e tests against:                ${E2E_HOST}"
-          echo "Host to run overlay e2e tests against:        ${NEXT_PUBLIC_OVERLAY_HOST}"
+          echo "URL to run e2e tests against:                 ${E2E_HOST}"
+          echo "URL to run overlay e2e tests against:         ${NEXT_PUBLIC_OVERLAY_HOST}"
           echo "Config for arithmetic e2e api tests:          ${ENTITY_ARITHMETIC_REQUEST_FOR_API_TESTS}"
           echo "Config for attachment request e2e api tests:  ${ENTITY_PLUS_ATTACHMENT_FOR_API_TESTS}"
           echo "Config for attachment response e2e api tests: ${ENTITY_SIMPLE_REQUEST_FOR_API_TESTS}"
@@ -197,15 +200,13 @@ jobs:
       - name: Generate Allure Report
         if: ${{ !cancelled() }}
         run: |
-          ./allure-${ALLURE_VERSION}/bin/allure generate ./apps/chat-e2e/allure-${{ matrix.target }}-results -o ./apps/chat-e2e/allure-${{ matrix.target }}-report --clean
+          allure generate ./apps/chat-e2e/allure-${{ matrix.target }}-results -o ./apps/chat-e2e/allure-${{ matrix.target }}-report --clean
         shell: bash
-        env:
-          ALLURE_VERSION: ${{ inputs.allure-version }}
       - name: Upload Allure Report
         uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
         if: ${{ !cancelled() }}
         with:
-          name: "${{ inputs.allure-report-prefix }}-${{ github.run_id }}-${{ matrix.target }}"
+          name: "${{ inputs.report-prefix }}-${{ matrix.target }}"
           path: |
             apps/chat-e2e/allure-${{ matrix.target }}-report
           retention-days: 30
