fix: wait for full DNS propagation before running E2E test

diff --git a/.github/workflows/gh-e2e-test.yml b/.github/workflows/gh-e2e-test.yml
--- a/.github/workflows/gh-e2e-test.yml
+++ b/.github/workflows/gh-e2e-test.yml
@@ -124,8 +124,53 @@ jobs:
           echo "Expected environment URL ${E2E_HOST}, waiting to be available..."
           ENV_HOSTNAME=$(echo "$E2E_HOST" | awk -F/ '{print $3}')
           ENV_OVERLAY_HOSTNAME=$(echo "$NEXT_PUBLIC_OVERLAY_HOST" | awk -F/ '{print $3}')
-          # Networkcalc.com service become unreliable so adding dummy delay to allow DNS propagation
-          sleep 30
+
+          wait_for_dns() {
+              DOMAIN="$1"
+              ATTEMPT=0
+              ATTEMPT_LIMIT=90  # retry resolve up to 15 minutes
+              ATTEMPT_DELAY=10  # 10 seconds between resolve attempts
+
+              if [ -z "$DOMAIN" ]; then
+                  echo "Specify domain name as first argument" >&2
+                  return 1
+              fi
+
+              if ! echo $DOMAIN | grep -Eq '^.+\.nightly-test\.deltixhub\.io'; then
+                  echo "Incorrect domain specified: $DOMAIN" >&2
+                  return 1
+              fi
+
+              NS_SERVERS=$(dig +short @8.8.8.8 ns nightly-test.deltixhub.io)
+              echo "Detected nameservers for $DOMAIN:"
+              echo "$NS_SERVERS"
+
+              for NS in $NS_SERVERS
+              do
+                  while true
+                      do
+                      echo "Query $NS for $DOMAIN"
+                      RESULT=$(dig +short @${NS} "$DOMAIN")
+                      if [ ! -z "$RESULT" ]; then
+                          if echo "$RESULT" | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
+                              echo "$RESULT"
+                              break
+                          fi
+                      fi
+                      ATTEMPT=$((ATTEMPT+1))
+                      if [ $ATTEMPT -le $ATTEMPT_LIMIT ]; then
+                          sleep $ATTEMPT_DELAY
+                      else
+                          echo "Unable to resolve $DOMAIN" >&2
+                          return 1
+                      fi
+                  done
+              done
+          }
+
+          wait_for_dns ${ENV_HOSTNAME}
+          wait_for_dns ${ENV_OVERLAY_HOSTNAME}
+
           curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${E2E_HOST}"/api/health
           curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${NEXT_PUBLIC_OVERLAY_HOST}"/api/health
         shell: bash
@@ -203,8 +248,53 @@ jobs:
           echo "Expected environment URL ${E2E_HOST}, waiting to be available..."
           ENV_HOSTNAME=$(echo "$E2E_HOST" | awk -F/ '{print $3}')
           ENV_OVERLAY_HOSTNAME=$(echo "$NEXT_PUBLIC_OVERLAY_HOST" | awk -F/ '{print $3}')
-          # Networkcalc.com service become unreliable so adding dummy delay to allow DNS propagation
-          sleep 30
+
+          wait_for_dns() {
+              DOMAIN="$1"
+              ATTEMPT=0
+              ATTEMPT_LIMIT=90  # retry resolve up to 15 minutes
+              ATTEMPT_DELAY=10  # 10 seconds between resolve attempts
+
+              if [ -z "$DOMAIN" ]; then
+                  echo "Specify domain name as first argument" >&2
+                  return 1
+              fi
+
+              if ! echo $DOMAIN | grep -Eq '^.+\.nightly-test\.deltixhub\.io'; then
+                  echo "Incorrect domain specified: $DOMAIN" >&2
+                  return 1
+              fi
+
+              NS_SERVERS=$(dig +short @8.8.8.8 ns nightly-test.deltixhub.io)
+              echo "Detected nameservers for $DOMAIN:"
+              echo "$NS_SERVERS"
+
+              for NS in $NS_SERVERS
+              do
+                  while true
+                      do
+                      echo "Query $NS for $DOMAIN"
+                      RESULT=$(dig +short @${NS} "$DOMAIN")
+                      if [ ! -z "$RESULT" ]; then
+                          if echo "$RESULT" | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
+                              echo "$RESULT"
+                              break
+                          fi
+                      fi
+                      ATTEMPT=$((ATTEMPT+1))
+                      if [ $ATTEMPT -le $ATTEMPT_LIMIT ]; then
+                          sleep $ATTEMPT_DELAY
+                      else
+                          echo "Unable to resolve $DOMAIN" >&2
+                          return 1
+                      fi
+                  done
+              done
+          }
+
+          wait_for_dns ${ENV_HOSTNAME}
+          wait_for_dns ${ENV_OVERLAY_HOSTNAME}
+
           curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${E2E_HOST}"/api/health
           curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${NEXT_PUBLIC_OVERLAY_HOST}"/api/health
         shell: bash
