chore: optimize wait for environment script towards generic approach

diff --git a/.github/workflows/gh-e2e-test.yml b/.github/workflows/gh-e2e-test.yml
--- a/.github/workflows/gh-e2e-test.yml
+++ b/.github/workflows/gh-e2e-test.yml
@@ -119,63 +119,66 @@ jobs:
         shell: bash
       - name: Wait for environment
         run: |
-          echo "Expected environment URL ${E2E_HOST}, waiting to be available..."
-          ENV_HOSTNAME=$(echo "$E2E_HOST" | awk -F/ '{print $3}')
-          ENV_OVERLAY_HOSTNAME=$(echo "$NEXT_PUBLIC_OVERLAY_HOST" | awk -F/ '{print $3}')
+          #!/bin/bash
+          echo "Expected environment URL ${ENVIRONMENT_URL}, waiting to be available..."
+          env_hostname=$(echo "$ENVIRONMENT_URL" | awk -F/ '{print $3}')
+          env_overlay_hostname=$(echo "$NEXT_PUBLIC_OVERLAY_HOST" | awk -F/ '{print $3}')
 
           wait_for_dns() {
-              DOMAIN="$1"
-              ATTEMPT=0
-              ATTEMPT_LIMIT=90  # retry resolve up to 15 minutes
-              ATTEMPT_DELAY=10  # 10 seconds between resolve attempts
+              local domain="$1"
+              local attempt=0
+              local attempt_limit=90  # retry resolve up to 15 minutes
+              local attempt_delay=10  # 10 seconds between resolve attempts
 
-              if [ -z "$DOMAIN" ]; then
+              if [ -z "$domain" ]; then
                   echo "Specify domain name as first argument" >&2
                   return 1
               fi
 
-              BASE_DOMAIN=$(echo "$DOMAIN" | sed -E 's/[^.]+\.(.+)/\1/')
-              echo "Query Google public DNS for $BASE_DOMAIN nameservers"
-              NS_SERVERS=$(dig +short @8.8.8.8 ns $BASE_DOMAIN)
-              if [ -n "$NS_SERVERS" ]; then
-                  echo "Detected nameservers for $BASE_DOMAIN:"
-                  echo "$NS_SERVERS"
+              local base_domain=$(echo "$domain" | sed -E 's/[^.]+\.(.+)/\1/')
+              echo "Query Google public DNS for $base_domain nameservers"
+              local ns_servers=$(dig +short @8.8.8.8 ns $base_domain)
+              if [ -n "$ns_servers" ]; then
+                  echo "Detected nameservers for $base_domain:"
+                  echo "$ns_servers"
               else
-                  echo "Unable to detect nameservers for $BASE_DOMAIN" >&2
+                  echo "Unable to detect nameservers for $base_domain" >&2
                   return 1
               fi
 
-              for NS in $NS_SERVERS
+              local ns
+              local result
+              for ns in $ns_servers
               do
                   while true
                       do
-                      echo "Query $NS for $DOMAIN"
-                      RESULT=$(dig +short @${NS} "$DOMAIN")
-                      if [ ! -z "$RESULT" ]; then
-                          if echo "$RESULT" | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
-                              echo "$RESULT"
+                      echo "Query $ns for $domain"
+                      result=$(dig +short @${ns} "$domain")
+                      if [ ! -z "$result" ]; then
+                          if echo "$result" | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
+                              echo "$result"
                               break
                           fi
                       fi
-                      ATTEMPT=$((ATTEMPT+1))
-                      if [ $ATTEMPT -le $ATTEMPT_LIMIT ]; then
-                          sleep $ATTEMPT_DELAY
+                      attempt=$((attempt+1))
+                      if [ $attempt -le $attempt_limit ]; then
+                          sleep $attempt_delay
                       else
-                          echo "Unable to resolve $DOMAIN" >&2
+                          echo "Unable to resolve $domain" >&2
                           return 1
                       fi
                   done
               done
           }
 
-          wait_for_dns ${ENV_HOSTNAME}
-          wait_for_dns ${ENV_OVERLAY_HOSTNAME}
+          wait_for_dns ${env_hostname}
+          wait_for_dns ${env_overlay_hostname}
 
-          curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${E2E_HOST}"/api/health
+          curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${ENVIRONMENT_URL}"/api/health
           curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${NEXT_PUBLIC_OVERLAY_HOST}"/api/health
         shell: bash
         env:
-          E2E_HOST: ${{ inputs.e2e-host }}
+          ENVIRONMENT_URL: ${{ inputs.e2e-host }}
           NEXT_PUBLIC_OVERLAY_HOST: ${{ inputs.next-public-overlay-host }}
       - name: Run tests
         run: |
