chore: test ci

diff --git a/.github/workflows/test_gradle_docker.yml b/.github/workflows/test_gradle_docker.yml
--- a/.github/workflows/test_gradle_docker.yml
+++ b/.github/workflows/test_gradle_docker.yml
@@ -21,22 +21,27 @@ env:
   GRADLE_USER_HOME: ${GITHUB_ACTION_PATH}/.gradle
 
 jobs:
-#  style_checks:
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#      - name: PR title check
-#        uses: thehanimo/pr-title-checker@0cf5902181e78341bb97bb06646396e5bd354b3f #v1.4.0
-#        with:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  style_checks:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: PR title check
+        uses: thehanimo/pr-title-checker@0cf5902181e78341bb97bb06646396e5bd354b3f #v1.4.0
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 #      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
 #      - name: Set up JDK
 #        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 #v3.12.0
 #        with:
 #          java-version: ${{ github.event.inputs.java_version }}
 #          distribution: ${{ github.event.inputs.java_distribution }}
-#      - name: Setup Gradle
-#        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc #v2.8.0
+#  - name: Cache gradle dependencies
+#    uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
+#    with:
+#      path: ~/.gradle/caches
+#      key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
+#      restore-keys: |
+#        ${{ runner.os }}-gradle-caches-
 #      - name: Codestyle
 #        continue-on-error: ${{ github.event.inputs.bypass_checks }}
 #        run: |
@@ -44,7 +49,6 @@ jobs:
 
   code_checks:
     runs-on: ubuntu-latest
-    #TODO: cache for libs
     steps:
       - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
         with:
@@ -54,30 +58,45 @@ jobs:
         with:
           java-version: ${{ inputs.java_version }}
           distribution: ${{ inputs.java_distribution }}
+      - name: Cache gradle dependencies
+        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
+        with:
+          path: ~/.gradle/caches
+          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
+          restore-keys: |
+              ${{ runner.os }}-gradle-caches-
       - name: Test
         continue-on-error: ${{ inputs.bypass_checks }}
         run: |
-          find ./gradle -type f -ls
-          jar -tvf ./gradle/wrapper/gradle-wrapper.jar
-          ./gradlew test || ( echo "::error::Tests failed" && exit 1)
-          find ./build -type f -ls
+          ./gradlew check || ( echo "::error::Tests failed" && exit 1)
       - name: Build
         run: ./gradlew build -x test
 
-#  docker_build:
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
-#      - name: Set up JDK
-#        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 #v3.12.0
-#        with:
-#          java-version: ${{ inputs.java_version }}
-#          distribution: ${{ inputs.java_distribution }}
-#      - name: Setup Gradle
-#        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc #v2.8.0
-#      - name: Build
-#        run: ./gradlew build -x test
+  docker_build:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
+      - name: Set up JDK
+        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 #v3.12.0
+        with:
+          java-version: ${{ inputs.java_version }}
+          distribution: ${{ inputs.java_distribution }}
+      - name: Cache gradle dependencies
+        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
+        with:
+          path: ~/.gradle/caches
+          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle-caches-
+      - name: Build
+        run: ./gradlew build -x test
+      - uses: epam/ai-dial-ci/actions/build_docker
+        with:
+          image_name: ${{ env.IMAGE_NAME }}
+          image_tag: test
+          push: false
+          scan: true
 #      - name: Build  Docker image
 #        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 #v4.2.1
 #        with:
@@ -93,11 +112,12 @@ jobs:
 #          #ignore-unfixed: true
 #          vuln-type: 'os,library'
 #          severity: 'CRITICAL,HIGH'
-#
-#  ort_scan:
-#    runs-on: ubuntu-latest
-#
-#    steps:
+
+  ort_scan:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: epam/ai-dial-ci/actions/ort
 #      - name: Use HTTPS instead of SSH for Git cloning
 #        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
 #      - name: Checkout project
