chore: test ci

diff --git a/.github/workflows/test_gradle_docker.yml b/.github/workflows/test_gradle_docker.yml
--- a/.github/workflows/test_gradle_docker.yml
+++ b/.github/workflows/test_gradle_docker.yml
@@ -35,6 +35,8 @@ jobs:
         with:
           java-version: ${{ github.event.inputs.java_version }}
           distribution: ${{ github.event.inputs.java_distribution }}
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc #v2.8.0
       - name: Codestyle
         continue-on-error: ${{ github.event.inputs.bypass_checks }}
         run: |
@@ -50,13 +52,11 @@ jobs:
         with:
           java-version: ${{ inputs.java_version }}
           distribution: ${{ inputs.java_distribution }}
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc #v2.8.0
       - name: Test
         continue-on-error: ${{ inputs.bypass_checks }}
-        run: |
-          find ./gradle -type f -ls
-          gradle
-          find ./gradle -type f -ls
-          ./gradlew test || ( echo "::error::Tests failed" && exit 1)
+        run: ./gradlew test || ( echo "::error::Tests failed" && exit 1)
       - name: Build
         run: ./gradlew build -x test
 
@@ -65,20 +65,13 @@ jobs:
 
     steps:
       - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
-      - name: gh data test
-        env:
-          JSON_DOC: ${{ toJSON(github) }}
-        run: echo "$JSON_DOC" | jq '.'
-      - name: test
-        run: |
-          echo ${{ inputs.bypass_checks }}
-          echo ${{ inputs.java_version }}
-          echo ${{ inputs.java_distribution }}
       - name: Set up JDK
         uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 #v3.12.0
         with:
           java-version: ${{ inputs.java_version }}
           distribution: ${{ inputs.java_distribution }}
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc #v2.8.0
       - name: Build
         run: ./gradlew build -x test
       - name: Build  Docker image
